---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp25-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp25-deploy
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 10
