apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp11-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app11
  template:
    metadata:
      labels:
        app: app11
    spec:
      containers:
      - name: app11
        image: alpine:edge
        args:
        - ash
        - -c
        - "while true; do echo v12; sleep 1; done"