---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp12-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app12
  template:
    metadata:
      labels:
        app: app12
    spec:
      containers:
      - name: app12
        image: jwilder/whoami:latest
        ports:
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: app12
spec:
  type: ClusterIP
  selector:
    app: app12
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000