---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp17-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app17
  template:
    metadata:
      labels:
        app: app17
    spec:
      volumes:
      - name: nginx-data
      containers:
      - name: app17
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-data
---
kind: Service
apiVersion: v1
metadata:
  name: app17
spec:
  type: ClusterIP
  selector:
    app: app17
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: app17-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app17
          servicePort: 80
      - path: /*
        backend:
          serviceName: app17
          servicePort: 80