---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp13-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app13
  template:
    metadata:
      labels:
        app: app13
    spec:
      containers:
      - name: app13
        image: webofmars/go-whoami:latest
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: app13
spec:
  type: NodePort
  selector:
    app: app13
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000