---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp26-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app26
  template:
    metadata:
      labels:
        app: app26
    spec:
      containers:
      - name: app26
        image: infrabuilder/glouton:latest
        resources:
          requests:
            cpu: "0.25"
          limits:
            cpu: "0.50"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp26-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp26-deploy
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 10
