---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim-2
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp19-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app19
  template:
    metadata:
      labels:
        app: app19
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim-2
      containers:
      - name: app19
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
---
kind: Service
apiVersion: v1
metadata:
  name: app19
spec:
  type: ClusterIP
  selector:
    app: app19
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: app19-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app19
          servicePort: 80
      - path: /*
        backend:
          serviceName: app19
          servicePort: 80